version: 2.1
jobs:
  build-and-test:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - run: |
           echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
           docker image build -t somkiat/circle .
           docker image push somkiat/circle
          
workflows:
    build-and-test:
      jobs:
        - build-and-test
