version: 2.1
orbs:
  docker: circleci/docker@1.3.0
jobs:
  build:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - run: |
           echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
           docker image build -t somkiat/circle .
           docker image push somkiat/circle
          
workflows:
    build-and-test:
      jobs:
        - build
